In [1]:
print("hello")
print(10+20)

hello
30


In [9]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
print(type(a))
print(np.ndim(a))

<class 'numpy.ndarray'>
1


In [15]:
a=[1,2,3,4]
b=[3,4,5,6]
# c=np.array(a)
# d=np.array(b)
c=np.array([a,b])

print(c)


[[1 2 3 4]
 [3 4 5 6]]
